# Generated by Django 2.1.1 on 2020-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(default='', max_length=200, verbose_name='职位名称')),
                ('companyFullName', models.CharField(default='', max_length=200, verbose_name='公司名称')),
                ('companySize', models.CharField(default='', max_length=200, verbose_name='公司规模')),
                ('education', models.CharField(default='', max_length=200, verbose_name='学历需求')),
                ('workYear', models.CharField(default='', max_length=200, verbose_name='工作经验')),
                ('skillLables', models.CharField(default='', max_length=200, verbose_name='所需技能')),
                ('salary', models.CharField(default='', max_length=200, verbose_name='工资待遇')),
                ('address', models.CharField(default='', max_length=200, verbose_name='办公地址')),
                ('createTime', models.CharField(default='', max_length=200, verbose_name='职位发布时间')),
            ],
        ),
    ]
